services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: clinicmitra-backend

    ports:
      - "3001:3001"

    env_file:
       - ./backend/.env

    restart: unless-stopped